#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: micro-product
#          uri: lb://MICRO-PRODUCT
#          predicates:
#            - Path=/api/products/**
#        - id: micro-user
#          uri: lb://MICRO-USER
#          predicates:
#            - Path=/api/users/**
#        - id: micro-order
#          uri: lb://MICRO-ORDER
#          predicates:
#            - Path=/api/orders/**, /api/cart/**
#        - id: micro-eureka
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        register-health-indicator: true
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
        sliding-window-size: 10